typography_spectrum: 0.4962053680792451
content_rating:
  adult: false
color:
  brandStrength: 0.6797691436950117
  lightness: 0.2777184038423002
  saturation: 0.2976176568772644
  rhythmicContrast: 0.938227531965822
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
opengraph:
  appId: '746875900'
  type: Facebook Page
layout_spectrum: 0.6675116720143706
author:
  name: Tristan Bayer
  email: creative@earthnative.com
  url: 'http://www.earthnative.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/202c4f07-7b8c-47ef-803a-f015d2b91b73.jpg
name: NATIVES.EARTH
navigation:
  - name: Earthnative Photography
    url: photo.earthnative.com
    type: external
  - name: 'Acid Test '
    url: 'http://acidtestmovie.com'
    type: external
  - name: Motion Pictures
    url: 'http://vimeo.com/earthnative'
    type: external
  - name: Fin Free
    url: 'http://finfree.org'
    type: external
  - name: Sonic Sea
    url: 'http://sonicsea.org'
    type: external
  - name: Revolution
    url: 'http://therevolutionmovie.com'
    type: external
  - name: Earthling Campaign
    url: 'http://earthlingmovie.com'
    type: external
  - name: ImmersiveTech
    url: 'http://immersivetech.com'
    type: external
  - name: Satellite Earth
    url: 'http://satelliteearth.com'
    type: external
  - name: Greater Consciousness
    url: 'http://greaterconsciousness.com'
    type: external
  - name: Creactivist
    url: 'http://creactivist.org'
    type: external
  - name: Earthnative
    url: 'http://earthnative.com'
    type: external
  - name: EarthNative Tumblr
    url: 'http://tumblr.com/earthnative'
    type: external
  - name: Tripping
    url: 'http://tripping.tv'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a70e2ac-26dc-48a3-8052-27b66932137b.jpg
title: 'Earth, our only home. Make it better.'
description: Create. Connect. Protect.
