layout_spectrum: 0.6675116720143706
typography_spectrum: 0.4962053680792451
color:
  brandStrength: 0.6797691436950117
  lightness: 0.2777184038423002
  saturation: 0.2976176568772644
  rhythmicContrast: 0.938227531965822
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: NATIVES.EARTH
navigation:
  - id: photo.earthnative.com
    url: photo.earthnative.com
    name: Earthnative Photography
    type: external
  - id: 'http://acidtestmovie.com'
    url: 'http://acidtestmovie.com'
    name: 'Acid Test '
    type: external
