typography_spectrum: 0.09661202458664775
content_rating:
  adult: false
color:
  brandStrength: 0.7750934483483434
  lightness: 0.8172243244480342
  saturation: 0.599065895890817
  rhythmicContrast: 0.2776939629111439
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
github: true
opengraph:
  appId: '746875900'
  type: Facebook Page
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/05cc4cf7-b80e-40eb-b4fc-fe192114908e.jpg
layout_spectrum: 0.0577919774223119
author:
  name: Tristan Bayer
  email: creative@earthnative.com
  url: 'http://www.earthnative.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/202c4f07-7b8c-47ef-803a-f015d2b91b73.jpg
name: NATIVES.EARTH
navigation:
  - name: Earthnative Photography
    url: photo.earthnative.com
    type: external
  - name: 'Acid Test Movie '
    url: 'http://acidtestmovie.com'
    type: external
  - name: Motion Pictures
    url: 'http://vimeo.com/earthnative'
    type: external
  - name: Fin Free Campaign
    url: 'http://finfree.org'
    type: external
  - name: Sonic Sea Film
    url: 'http://sonicsea.org'
    type: external
  - name: Revolution
    url: 'http://therevolutionmovie.com'
    type: external
  - name: Earthling Campaign
    url: 'http://earthlingmovie.com'
    type: external
  - name: ImmersiveTech
    url: 'http://immersivetech.com'
    type: external
  - name: Satellite Earth
    url: 'http://satelliteearth.com'
    type: external
  - name: Greater Consciousness
    url: 'http://greaterconsciousness.com'
    type: external
  - name: Creactivist
    url: 'http://creactivist.org'
    type: external
  - name: Earthnative
    url: 'http://earthnative.com'
    type: external
  - name: EarthNative Tumblr
    url: 'http://tumblr.com/earthnative'
    type: external
  - name: Tripping
    url: 'http://tripping.tv'
    type: external
  - name: Orangutans are Pongos.
    id: d3bb360c-cf24-4271-b08a-0bda63c8eae4
    type: content
  - name: Polar Bears Vanishing Into Thin Ice
    id: e206e56f-fbc2-489c-a45d-91b868afc47d
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a70e2ac-26dc-48a3-8052-27b66932137b.jpg
title: 'Earth, our only home. Make it better.'
content: []
description: Create. Connect. Protect.
purpose:
  - type: contact
    url: 'mailto:contact@earthnative.com'
    label: Let's Work Together
  - type: external
    url: 'http://photos.earthnative.com'
    label: Scope Projects
